export const DEFAULT_LANGUAGE = 'zh';

export const LANGUAGE_OPTIONS = [
  { id: 'zh', label: 'CN' },
  { id: 'en', label: 'EN' },
];

const COPY = {
  zh: {
    pageTitle: 'Kiddomap · 3 分钟决定去哪',
    pageDescription: '3 分钟帮你决定今天带娃去哪。',
    tagline: '少一点纠结，多一点亲子时光',
    headline: '今天带娃去哪儿',
    filters: {
      age: '孩子年龄',
      area: '出发区域',
      time: '今天打算玩多久',
      energy: '更轻松的选择',
      ageOptions: {
        any: '不限',
        baby: '0-3 岁',
        little: '4-7 岁',
        big: '8 岁以上',
      },
      areaOptions: {
        any: '不限',
        klcc: 'KLCC',
        pj: 'PJ',
        'mont-kiara': 'Mont Kiara',
        bangsar: 'Bangsar',
      },
      timeOptions: {
        any: '不限',
        quick: '1-2 小时',
        easy: '2-3 小时',
        'half-day': '半天',
      },
      energyOptions: {
        any: '直接给我推荐',
        indoor: '下雨也能去',
        outdoor: '户外',
        budget: '预算友好',
      },
    },
    card: {
      bestPick: '当前最佳推荐',
      whyToday: '为什么推荐今天去',
      kidFit: '适合年龄',
      time: '大概玩多久',
      parentEnergy: '家长会不会累',
      driveCheck: '路程参考',
      cost: '花费',
      age: '年龄',
      takeMeThere: '带我去这里',
      showMore: '看看更多选择',
      hideOptions: '收起选项',
      takeThisOne: '就选这个',
      showAnother: '换一组推荐',
      backupPicks: '另外两个备选',
      showOnlyThree: '只看这 3 个',
      exploreFullMap: '查看完整地图',
      drivePrompt: '先选出发区域',
      area: '区域',
      tapToExplore: '点开看看',
    },
    saved: {
      button: '已收藏',
      title: '已收藏地点',
      empty: '点开任意地点卡里的爱心，就会收进这里。',
      close: '关闭',
    },
    detail: {
      shouldWeGo: '值得去吗？',
      beforeYouGo: '出发前先看',
      openingHours: '开放时间',
      bestTiming: '什么时候去更合适',
      watchOut: '有什么要注意',
      whatToPack: '带什么更稳',
      openTicketSite: '打开购票页',
      noTicketNeeded: '不用买票',
      justCheckConditions: '先看开放情况',
      freeNote: '免费地点更看天气和时间。',
      checkBeforeYouGo: '去之前先确认',
      walkInUsuallyWorks: '一般可直接到场',
      walkInNote: '有些地方会临时调整票价或入场规则。',
      buyTicketBeforeYouGo: '最好先买票',
      officialSiteFirst: '先看官网',
      walkInAvailable: '现场也可处理',
      officialSiteNote: '出发前先看官网最新信息。',
      genericTicketTitle: '出发前先确认门票',
      genericTicketNote: '如果有官网门票，先用官网，不要先跳第三方。',
      driveUnknown: '先选出发区域，再看大概车程。',
      save: '收藏',
      close: '关闭',
      takeMeThere: '带我去这里',
      ratingReviews: '评价',
      parentsLike: '家长更喜欢',
      goodChoiceIndoor: '如果你想找一个不太受天气影响的方案，这里值得考虑。',
      goodChoiceOutdoor: '如果你想趁天气还舒服带孩子出门，这里值得考虑。',
    },
    nav: {
      title: '选择导航方式',
      subtitle: '前往',
      google: 'Google 地图',
      googleNote: '熟悉、顺手，也方便看公交',
      waze: 'Waze',
      wazeNote: '更适合开车看实时路况',
      grab: 'Grab',
      grabNote: '直接打车，或者先打开网页',
      cancel: '取消',
    },
    footer: {
      summary: 'Kiddomap 帮吉隆坡家庭更快决定去哪玩，把周末过得更轻松。',
      explore: '探索',
      about: '关于',
      links: {
        indoor: '室内去处',
        rainy: '雨天去处',
        free: '免费去处',
        about: '关于 Kiddomap',
        contact: '联系我们',
        privacy: '隐私政策',
        terms: '使用条款',
      },
    },
    recommendation: {
      rainSafeIndoorPick: '下雨也能去',
      weatherFriendly: '天气友好再去',
      ageRange: (min, max) => `${min}-${max} 岁`,
      durationHours: value => `${value} 小时`,
      whyTodayRainSafe: '今天下雨也合适，不用反复看天气。',
      whyTodayIndoorAfternoon: '天气热或突然下雨时，室内更稳妥。',
      whyTodayOutdoorMorning: '趁天还没太热，早点出发更舒服。',
      whyTodayWeatherFriendly: '看天气合适就去，别拖到最热的时候。',
      kidFit: (min, max) => `更适合 ${min}-${max} 岁孩子。`,
      quickTime: hours => `${hours}，吃饭前后也能塞进去。`,
      halfDayTime: hours => `${hours}`,
      easyMode: '轻松模式',
      easyModeDetail: '冷气、厕所、吃饭都方便，家长没那么累。',
      mediumEasy: '还算轻松',
      mediumEasyDetail: '大致好走，但还是会有一点来回移动。',
      lightAdventure: '轻量出门',
      lightAdventureDetail: '户外也能玩，不至于把整天都耗光。',
      highEnergy: '更费体力',
      highEnergyDetail: '孩子会喜欢，但家长要准备好走动和天气变化。',
      weekendParent: label => `${label}，周末更省心。`,
      drive: '路程参考',
      driveUnknown: '先选出发区域',
      driveUnknownDetail: '选了区域后再看大概车程。',
      driveValue: (minutes, areaLabel) => `约 ${minutes} 分钟 · 从 ${areaLabel} 出发`,
      driveDetail: '按距离粗估，不是实时路况。',
      frictionIndoorPaid: '周末人多时，最好先订票。',
      frictionIndoor: '天气风险低，适合不想多想就出门。',
      frictionFree: '免费，最好避开最热的时候。',
      frictionOutdoor: '先看天气，再尽量避开正午。',
      contrastFree: '免费进入',
      contrastBudget: '更省钱',
      contrastRainSafe: '雨天更稳',
      contrastOutdoor: '更适合户外',
      contrastEasy: '更轻松',
      contrastQuick: '更快成行',
      contrastLonger: '能玩更久',
      contrastAnother: '换个感觉',
    },
  },
  en: {
    pageTitle: 'Kiddomap · Decide in 3 minutes',
    pageDescription: 'Pick a kid-friendly Kuala Lumpur place in 3 minutes.',
    tagline: 'Less Deciding, More Family Time',
    headline: 'Decide where to take your kid in 3 minutes.',
    filters: {
      age: 'Kid age',
      area: 'Starting area',
      time: 'Time today',
      energy: 'Lighter picks',
      ageOptions: {
        any: 'Any age',
        baby: '0-3',
        little: '4-7',
        big: '8+',
      },
      areaOptions: {
        any: 'Anywhere',
        klcc: 'KLCC',
        pj: 'PJ',
        'mont-kiara': 'Mont Kiara',
        bangsar: 'Bangsar',
      },
      timeOptions: {
        any: 'Any time',
        quick: '1-2h',
        easy: '2-3h',
        'half-day': 'Half day',
      },
      energyOptions: {
        any: 'Best answer',
        indoor: 'Rain-safe',
        outdoor: 'Outdoor',
        budget: 'Budget',
      },
    },
    card: {
      bestPick: 'Best pick right now',
      whyToday: 'Why today',
      kidFit: 'Kid fit',
      time: 'Time',
      parentEnergy: 'Parent energy',
      driveCheck: 'Drive check',
      cost: 'Cost',
      age: 'Age',
      takeMeThere: 'Take me there',
      showMore: 'Show me more',
      hideOptions: 'Hide options',
      takeThisOne: 'Take this one',
      showAnother: 'Show me another good spot',
      backupPicks: 'Two backup picks',
      showOnlyThree: 'Show only these 3 picks',
      exploreFullMap: 'Explore full map',
      drivePrompt: 'Pick your start area',
      area: 'Area',
      tapToExplore: 'Tap to explore',
    },
    saved: {
      button: 'Saved',
      title: 'Saved spots',
      empty: 'Tap the heart inside any place card to save it here.',
      close: 'Close',
    },
    detail: {
      shouldWeGo: 'Should we go?',
      beforeYouGo: 'Before you go',
      openingHours: 'Opening hours',
      bestTiming: 'Best timing',
      watchOut: 'Watch out',
      whatToPack: 'What to pack',
      openTicketSite: 'Open ticket site',
      noTicketNeeded: 'No ticket needed',
      justCheckConditions: 'Just check opening conditions',
      freeNote: 'Free places are fastest when weather and timing match.',
      checkBeforeYouGo: 'Check before you go',
      walkInUsuallyWorks: 'Walk-in usually works',
      walkInNote: 'Some places still change rates or entry rules without much notice.',
      buyTicketBeforeYouGo: 'Buy ticket before you go',
      officialSiteFirst: 'Official site first',
      walkInAvailable: 'Walk-in available',
      officialSiteNote: 'Check the official site before you go.',
      genericTicketTitle: 'Check tickets before you go',
      genericTicketNote: 'If official tickets exist, use them before Klook or Traveloka.',
      driveUnknown: 'Pick your start area to see a rough drive time.',
      save: 'Save',
      close: 'Close',
      takeMeThere: 'Take me there',
      ratingReviews: 'Reviews',
      parentsLike: 'Parents like',
      goodChoiceIndoor: 'Good choice if you want a low-weather-risk plan.',
      goodChoiceOutdoor: 'Good choice if you want fresh air before it gets hot.',
    },
    nav: {
      title: 'Pick a map app',
      subtitle: 'Go to',
      google: 'Google Maps',
      googleNote: 'Easy, familiar, and good for transit too',
      waze: 'Waze',
      wazeNote: 'Live traffic, great for driving in KL',
      grab: 'Grab',
      grabNote: 'Open Grab app or book on the web',
      cancel: 'Cancel',
    },
    footer: {
      summary: 'Kiddomap helps Kuala Lumpur families create easier, happier weekends. We curate kid-friendly places and practical notes so parents can spend less time deciding and more time enjoying the day.',
      explore: 'Explore',
      about: 'About',
      links: {
        indoor: 'Indoor places in KL',
        rainy: 'Rainy day ideas',
        free: 'Free places',
        about: 'About',
        contact: 'Contact',
        privacy: 'Privacy Policy',
        terms: 'Terms of Use',
      },
    },
    recommendation: {
      rainSafeIndoorPick: 'Rain-safe indoor pick',
      weatherFriendly: 'Best when the sky looks friendly',
      ageRange: (min, max) => `Age ${min}-${max}`,
      durationHours: value => `${value}h`,
      whyTodayRainSafe: 'Rain-safe, no sky-check needed.',
      whyTodayIndoorAfternoon: 'A/C cover if KL turns hot or rainy.',
      whyTodayOutdoorMorning: 'Better before the day gets hot.',
      whyTodayWeatherFriendly: 'Go only if the sky still looks friendly.',
      kidFit: (min, max) => `Best for age ${min}-${max}.`,
      quickTime: hours => `${hours}, easy to fit between meals.`,
      halfDayTime: hours => `${hours}, more like a half-day plan.`,
      easyMode: 'Easy mode',
      easyModeDetail: 'A/C, toilets, food nearby. Parents can breathe.',
      mediumEasy: 'Medium easy',
      mediumEasyDetail: 'Mostly sheltered, but expect some moving around.',
      lightAdventure: 'Light adventure',
      lightAdventureDetail: 'Outdoor fun without turning the whole day into a mission.',
      highEnergy: 'High energy',
      highEnergyDetail: 'Kids may love it, but parents should expect heat and walking.',
      weekendParent: label => `${label}: weekend-friendly, lower planning load.`,
      drive: 'Drive',
      driveUnknown: 'Pick your start area',
      driveUnknownDetail: 'Add an area to see a rough drive time.',
      driveValue: (minutes, areaLabel) => `~${minutes} min from ${areaLabel}`,
      driveDetail: 'Rough estimate based on distance, not live traffic.',
      frictionIndoorPaid: 'Book ahead if it is a busy weekend.',
      frictionIndoor: 'Low weather risk, easy to start without overthinking.',
      frictionFree: 'Free entry. Best before it gets too hot.',
      frictionOutdoor: 'Check the sky first, then go before peak afternoon heat.',
      contrastFree: 'Free entry',
      contrastBudget: 'Budget pick',
      contrastRainSafe: 'Rain-safe',
      contrastOutdoor: 'Outdoor pick',
      contrastEasy: 'Less effort',
      contrastQuick: 'Quicker trip',
      contrastLonger: 'Stay longer',
      contrastAnother: 'Another pick',
    },
  },
};

export function getCopy(language = DEFAULT_LANGUAGE) {
  return COPY[language] || COPY[DEFAULT_LANGUAGE];
}
